name: run-test-cases
run-name: run-test-cases
on:
  push:
#    paths:
#      - 'server/**'
    branches:
      - test
      - main
jobs:
  test-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install and test-db
        run: |
          cd server
          npm i
          echo "MONGO_URI='mongodb+srv://prath:1234@crowdcontract.ji7u87b.mongodb.net'
                PORT=5051
                JWT_SECRET_KEY='7de4afd53ba6eae584e0b6281bea2030d99a5971c6585a2b93ddc206dcff271651b44472cfb54acf01cb76b6eb8a2d9caa0251a3a40e7e666475822a11c7ce89'
                AES_SECRET_KEY='2a953982e33475be953e3cadaa2b11e15a7790299e5be36e4022b1e84d3d495a273817b18a85246d6414e62d062d633654ecd3876841b714e78d6765f8648006'
                SALT_ROUNDS=5" > .env
          npm run test-db
          echo "MONGO_URI='mongodb+srv://prath:1234@crowdcontract.ji7u87b.mongodb.net/crowdContract'
                PORT=5051
                JWT_SECRET_KEY='7de4afd53ba6eae584e0b6281bea2030d99a5971c6585a2b93ddc206dcff271651b44472cfb54acf01cb76b6eb8a2d9caa0251a3a40e7e666475822a11c7ce89'
                AES_SECRET_KEY='2a953982e33475be953e3cadaa2b11e15a7790299e5be36e4022b1e84d3d495a273817b18a85246d6414e62d062d633654ecd3876841b714e78d6765f8648006'
                SALT_ROUNDS=5" > .env

          npm run test-api
          rm .env
      - name: Archive logs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: db-test-logs
          path: |
             ${GITHUB_WORKSPACE}/server/logs/service.log
